import {test,expect,vi}from'vitest';
import {loadConfig}from'../src/config.js';import {GumloopClient}from'../src/api/client.js';import {ALL_TOOLS,validateArguments}from'../src/tools/index.js';import {createApp} from '../src/app.js';import {connect as slipwayConnect} from '@thenavidm/slipway/testing';import {readFile,writeFile,stat,symlink}from'node:fs/promises';import {mkdtempSync}from'node:fs';import {tmpdir}from'node:os';import {join}from'node:path';

/** The write policy comes from the environment on Slipway, as it does in use: this is the one a config describes. */
function policy(prefix:string,config:{readOnly?:boolean;allowDestructive?:boolean;auditPath?:string}):Record<string,string>{return{...(config.readOnly?{[`${prefix}_READ_ONLY`]:'1'}:{}),...(config.allowDestructive===false?{[`${prefix}_ALLOW_DESTRUCTIVE`]:'0'}:{}),...(config.auditPath?{[`${prefix}_AUDIT_LOG`]:config.auditPath}:{})};}
/** Slipway's schema check answers in the MCP SDK's own plain text, "Input validation error: …"; these tests read every error as JSON, so it is wrapped as {error}. */
function jsonError(r:any){const text=r.content?.[0]?.text??'';try{JSON.parse(text);return r;}catch{return{...r,content:[{type:'text',text:JSON.stringify({error:text})}]};}}
/** The SDK client's calls these tests were written against, over the real Slipway server. A hidden tool is a protocol error there; it comes back as the error result a client sees. */
function adapt(mcp:Awaited<ReturnType<typeof slipwayConnect>>){return{listTools:async()=>({tools:await mcp.listTools()}),callTool:async({name,arguments:args}:{name:string;arguments?:Record<string,unknown>}):Promise<any>=>{try{const r:any=await mcp.callTool(name,args??{});return r.isError?jsonError(r):r;}catch(e){return{isError:true,content:[{type:'text',text:JSON.stringify({error:(e as Error).message})}]};}},close:()=>mcp.close()};}
/** One tool call through the real server, as the 2.x guard-and-handler helper made it: the result's data, or its error thrown. */
async function viaServer(prefix:string,config:any,client:any,name:string,args:Record<string,unknown>):Promise<any>{const mcp=await slipwayConnect(createApp({context:()=>({config,client})}),{env:policy(prefix,config)});try{const r:any=await mcp.callTool(name,args);const text=(r.content as any[])?.[0]?.text??'';if(r.isError)throw new Error(text);try{return JSON.parse(text);}catch{return text;}}finally{await mcp.close();}}
const config=(extra:Record<string,string>={})=>loadConfig({GUMLOOP_API_KEY:'fixture-key',GUMLOOP_USER_ID:'fixture-user',GUMLOOP_MIN_REQUEST_INTERVAL_MS:'0',...extra});
const ok=(data:unknown)=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
async function call(name:string,args:Record<string,unknown>,client:GumloopClient){return viaServer('GUMLOOP',client.config,client,name,args);}
test('flow approval enforced before any fetch',async()=>{const f=vi.fn();await expect(call('start_flow',{saved_item_id:'flow'},new GumloopClient(config(),f))).rejects.toThrow('confirm');expect(f).not.toHaveBeenCalled()});
test('read-only direct confirmed run refused',async()=>{const f=vi.fn();await expect(call('start_flow',{saved_item_id:'flow',confirm:true},new GumloopClient(config({GUMLOOP_READ_ONLY:'1'}),f))).rejects.toThrow(/READ_ONLY|not found/);expect(f).not.toHaveBeenCalled()});
test('operation-disable policy rejects confirmed run',async()=>{const f=vi.fn();await expect(call('start_flow',{saved_item_id:'flow',confirm:true},new GumloopClient(config({GUMLOOP_ALLOW_DESTRUCTIVE:'0'}),f))).rejects.toThrow('ALLOW_DESTRUCTIVE');expect(f).not.toHaveBeenCalled()});
test('flow uses current top-level input schema and retains api/v1',async()=>{const f=vi.fn(async()=>ok({run_id:'fixture'}));await call('start_flow',{payload:{saved_item_id:'flow',recipient:'example@example.com'},confirm:true},new GumloopClient(config(),f));const [u,i]=f.mock.calls[0]as unknown as[URL,RequestInit];expect(u.href).toBe('https://api.gumloop.com/api/v1/start_pipeline');expect(JSON.parse(i.body as string)).toEqual({saved_item_id:'flow',recipient:'example@example.com',user_id:'fixture-user'});expect((i.headers as Record<string,string>).Authorization).toBe('Bearer fixture-key');expect((i.headers as Record<string,string>)['x-auth-key']).toBe('fixture-user');expect(i.redirect).toBe('error')});
test('named profiles never inherit another key or identity',async()=>{const f=vi.fn(async()=>ok({agents:[]}));const c=config({GUMLOOP_ACCOUNTS:JSON.stringify([{name:'selected',api_key:'different-key',user_id:'different-user'}])});await call('list_agents',{account:'selected'},new GumloopClient(c,f));expect(((f.mock.calls[0]as unknown as[URL,RequestInit])[1].headers as Record<string,string>)).toMatchObject({Authorization:'Bearer different-key','x-auth-key':'different-user'});expect(JSON.stringify(f.mock.calls)).not.toContain('fixture-key')});
test('legacy reads require a deliberate profile identity',async()=>{const f=vi.fn();await expect(call('list_flows',{},new GumloopClient(config({GUMLOOP_USER_ID:''}),f))).rejects.toThrow('user_id');expect(f).not.toHaveBeenCalled()});
test('private team defaults map to legacy project query',async()=>{const f=vi.fn(async()=>ok({workbooks:[]}));await call('list_workbooks',{},new GumloopClient(config({GUMLOOP_TEAM_ID:'team-fixture'}),f));const u=(f.mock.calls[0]as unknown as[URL])[0];expect(u.searchParams.get('project_id')).toBe('team-fixture');expect(u.searchParams.get('user_id')).toBe('fixture-user')});
test('history requires a selected saved item or workbook',async()=>{const f=vi.fn();await expect(call('get_run_history',{},new GumloopClient(config(),f))).rejects.toThrow('saved_item_id');expect(f).not.toHaveBeenCalled()});
test('malformed body and mixed file/flat body refuse before fetch',async()=>{const f=vi.fn();await expect(call('start_flow',{payload:{},confirm:true},new GumloopClient(config(),f))).rejects.toThrow();await expect(call('start_flow',{saved_item_id:'x',payload_file:'/unused',confirm:true},new GumloopClient(config(),f))).rejects.toThrow('mixing');expect(f).not.toHaveBeenCalled()});
test('missing flow user in full payload can use isolated profile',async()=>{const f=vi.fn(async()=>ok({run_id:'fixture'}));await call('start_flow',{payload:{saved_item_id:'flow'},confirm:true},new GumloopClient(config(),f));expect(JSON.parse((f.mock.calls[0]as unknown as[URL,RequestInit])[1].body as string).user_id).toBe('fixture-user')});
test('write timeouts never resubmit an unknown flow',async()=>{const f=vi.fn(async()=>{throw new Error('lost response')});await expect(call('start_flow',{saved_item_id:'flow',confirm:true},new GumloopClient(config(),f))).rejects.toThrow('No automatic retry');expect(f).toHaveBeenCalledTimes(1)});
test('write 429 never retries',async()=>{const f=vi.fn(async()=>new Response('{}',{status:429,headers:{'retry-after':'0'}}));await expect(call('start_flow',{saved_item_id:'flow',confirm:true},new GumloopClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('read 429 retries only with an explicit short header',async()=>{let n=0;const f=vi.fn(async()=>++n===1?new Response('{}',{status:429,headers:{'retry-after':'0'}}):ok({agents:[]}));const sleeps:number[]=[];await call('list_agents',{},new GumloopClient(config(),f,async(ms)=>{sleeps.push(ms)}));expect(f).toHaveBeenCalledTimes(2);expect(sleeps).toEqual([100])});
test('read 429 absent/long headers do not guess a window',async()=>{for(const headers of[{}, {'retry-after':'60'}]){const f=vi.fn(async()=>new Response('{}',{status:429,headers}));await expect(call('list_agents',{},new GumloopClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)}});
test('fixed origins refuse path escapes and arbitrary header injection',async()=>{const f=vi.fn();const c=new GumloopClient(config(),f);for(const p of['//evil.example','/../agents','/%2e%2e/agents','/%2f%2fevil'])await expect(c.request('GET',p)).rejects.toThrow('path');await expect(c.request('GET','/agents',[],undefined,undefined,'api','application/json',{Authorization:'injected'})).rejects.toThrow('header');expect(f).not.toHaveBeenCalled()});
test('nonstreaming chat uses only the reviewed ws origin',async()=>{const f=vi.fn(async()=>ok({choices:[]}));await call('create_chat_completion',{payload:{model:'fixture',messages:[{role:'user',content:'hello'}],stream:false},confirm:true},new GumloopClient(config(),f));expect((f.mock.calls[0]as unknown as[URL])[0].href).toBe('https://ws.gumloop.com/api/v1/chat/completions')});
test('streaming requests are rejected before network',async()=>{const f=vi.fn();await expect(call('create_chat_completion',{payload:{model:'fixture',messages:[{role:'user',content:'hello'}],stream:true},confirm:true},new GumloopClient(config(),f))).rejects.toThrow();expect(f).not.toHaveBeenCalled()});
test('multipart reads only approved regular files and sends native FormData',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-upload-'));const file=join(dir,'SKILL.md');await writeFile(file,'# Fixture');const f=vi.fn(async()=>ok({id:'skill'}));await call('create_skill',{files:[file],confirm:true},new GumloopClient(config(),f));const body=(f.mock.calls[0]as unknown as[URL,RequestInit])[1].body;expect(body).toBeInstanceOf(FormData);expect(((body as FormData).get('files')as File).name).toBe('SKILL.md');expect(await((body as FormData).get('files')as File).text()).toBe('# Fixture')});
test('multipart symlink refuses before upload',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-link-'));await writeFile(join(dir,'real'),'fixture');await symlink(join(dir,'real'),join(dir,'link'));const f=vi.fn();await expect(call('create_skill',{files:[join(dir,'link')],confirm:true},new GumloopClient(config(),f))).rejects.toThrow('non-symlink');expect(f).not.toHaveBeenCalled()});
test('signed artifact credential is confined to exclusive private file',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-result-'));const file=join(dir,'result.json');const f=vi.fn(async()=>ok({download_url:'https://files.example/a?X-Amz-Signature=fixture',file_name:'a.txt'}));const result=await call('download_artifact_file',{artifact_id:'artifact',output_file:file},new GumloopClient(config(),f));expect(JSON.stringify(result)).not.toContain('X-Amz-Signature');expect(JSON.parse(await readFile(file,'utf8')).download_url).toContain('X-Amz-Signature');if(process.platform!=='win32')expect((await stat(file)).mode&0o777).toBe(0o600);await expect(call('download_artifact_file',{artifact_id:'artifact',output_file:file},new GumloopClient(config(),f))).rejects.toThrow();expect(f).toHaveBeenCalledTimes(1)});
test('binary ZIP download saves bytes instead of treating them as JSON',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-zip-'));const file=join(dir,'files.zip');const bytes=new Uint8Array([80,75,3,4,1,2]);const f=vi.fn(async()=>new Response(bytes,{headers:{'Content-Type':'application/zip'}}));const result:any=await call('download_files',{file_names:['fixture.txt'],run_id:'run',output_file:file},new GumloopClient(config(),f));expect(new Uint8Array(await readFile(file))).toEqual(bytes);expect(result.bytes).toBe(6)});
test('private token overrides env and is redacted from provider errors/results',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-key-'));const file=join(dir,'key');await writeFile(file,'file-fixture-key',{mode:0o600});const f=vi.fn(async()=>ok({api_key:'file-fixture-key',echo:'file-fixture-key',url:'https://files.example/a?token=private'}));const result=await call('list_agents',{},new GumloopClient(config({GUMLOOP_TOKEN_FILE:file}),f));expect(JSON.stringify(result)).not.toContain('file-fixture-key');expect(JSON.stringify(result)).not.toContain('token=private');expect(((f.mock.calls[0]as unknown as[URL,RequestInit])[1].headers as Record<string,string>).Authorization).toBe('Bearer file-fixture-key')});
test('account discovery is network-free and excludes secrets and IDs',async()=>{const f=vi.fn();const data=await call('list_accounts',{},new GumloopClient(config(),f));expect(JSON.stringify(data)).not.toContain('fixture-key');expect(JSON.stringify(data)).not.toContain('fixture-user');expect(f).not.toHaveBeenCalled()});

test('approved local flow file upload encodes actual bytes with its name',async()=>{const dir=mkdtempSync(join(tmpdir(),'gumloop-base64-'));const file=join(dir,'fixture.txt');await writeFile(file,'local fixture');const f=vi.fn(async()=>ok({success:true}));await call('upload_file',{file_path:file,confirm:true},new GumloopClient(config(),f));const body=JSON.parse((f.mock.calls[0]as unknown as[URL,RequestInit])[1].body as string);expect(body.file_name).toBe('fixture.txt');expect(Buffer.from(body.file_content,'base64').toString()).toBe('local fixture');expect(body.file_path).toBeUndefined()});
test('local upload rejects mixed body routes before transmitting bytes',async()=>{const f=vi.fn();await expect(call('upload_file',{file_path:'/unused',file_content:'Zm9v',confirm:true},new GumloopClient(config(),f))).rejects.toThrow('cannot mix');expect(f).not.toHaveBeenCalled()});

test('credit-consuming Brain search needs explicit confirmation before fetch',async()=>{const f=vi.fn();await expect(call('search_brain',{query:'fixture'},new GumloopClient(config(),f))).rejects.toThrow('confirm');expect(f).not.toHaveBeenCalled()});
